name = "CosmoParticles"
uuid = "b2fead7a-f6ae-4e5b-9c3d-9b85ace3042d"
authors = ["Lucas Valenzuela"]
version = "0.1.0"

[deps]
FastUnitfulOperations = "b031420d-871e-4e9c-8878-33bec386257e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
